//
//  ProductListModels.swift
//  ProductStoreDemo
//
//  Created by Pit on 12/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductList{
    
    // MARK: Use cases
    enum List{
        
        struct Request{ }
        
        struct Response{
            var productList: [ProductModel]
        }
        
        struct ViewModel{
            struct Product{
                var title: String
                var image: String
                var isNewProduct: Bool
                var price: Float
            }
            var productList: [Product]
        }
        
        struct Error{
            var errorDescription: String
        }
    }
}
