//
//  ProductDetailModels.swift
//  ProductStoreDemo
//
//  Created by Pit on 12/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail
{
    // MARK: Use cases
    enum Detail{
        
        struct Request { }
        
        struct Response {
            var product: ProductModel
        }
        
        struct ViewModel {
            struct Product{
                var id: Int
                var title: String
                var image: String
                var content: String
                var isNewProduct: Bool
                var price: Float
            }
            var product: Product
        }
    }
}
