//
//  ProductDetailRouter.swift
//  ProductStoreDemo
//
//  Created by Pit on 12/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDetailRoutingLogic{
    @objc func popViewController()
}

protocol ProductDetailDataPassing{
    var dataStore: ProductDetailDataStore? { get }
}

class ProductDetailRouter: NSObject, ProductDetailRoutingLogic, ProductDetailDataPassing{
    
    weak var viewController: ProductDetailViewController?
    var dataStore: ProductDetailDataStore?

    func popViewController(){
        self.viewController?.navigationController?.popViewController(animated: true)
    }
}
