//
//  ProductDetailInteractor.swift
//  ProductStoreDemo
//
//  Created by Pit on 12/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailBusinessLogic{
    func getProductDetail(request: ProductDetail.Detail.Request)
}

protocol ProductDetailDataStore{
    var currentProduct: ProductModel { get set }
}

class ProductDetailInteractor: ProductDetailBusinessLogic, ProductDetailDataStore{
    
    var presenter: ProductDetailPresentationLogic?
    var worker: ProductDetailWorker?
    
    var currentProduct: ProductModel = ProductModel()
    
    func getProductDetail(request: ProductDetail.Detail.Request){

        let response = ProductDetail.Detail.Response(product: currentProduct)
        self.presenter?.presentProductDetail(response: response)
    }
}
