//
//  ProductListWorkerTests.swift
//  ProductStoreDemo
//
//  Created by Pit on 15/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ProductStoreDemo
import XCTest

class ProductListWorkerTests: XCTestCase{
    
    // MARK: Subject under test
    
    var sut: ProductListWorker!
    
    // MARK: Test lifecycle
    
    override func setUp(){
        super.setUp()
        setupProductListWorker()
    }
    
    override func tearDown(){
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductListWorker(){
        
        sut = ProductListWorker()
    }
    
    // MARK: Test doubles
    
    class ProductAPISpy: ProductAPI{
        
        var getProductListCalled: Bool = false
        override func getProductList(completion: @escaping([ProductModel]) -> Void, failure: @escaping (String) -> Void){
            getProductListCalled = true
        }
        
        var getProductByIdCalled: Bool = false
        override func getProduct(by id: Int, completion: @escaping(ProductModel) -> Void, failure: @escaping (String) -> Void){
            getProductByIdCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldGetProductList(){
        
        // Given
        let spy = ProductAPISpy()
        
        // When
        spy.getProductList { (productList: [ProductModel]) in
            
        } failure: { (error: String) in
            
        }

        // Then
        XCTAssertTrue(spy.getProductListCalled, "getProductList() should ask the api to get product list")
    }
}
